//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCWITHSIGNALR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public string Title { get; set; }
        public string Url { get; set; }
        public string Platform { get; set; }
        public string Score { get; set; }
        public string Genre { get; set; }
        public string Editors_choice { get; set; }
        public string Release_year { get; set; }
        public int ID { get; set; }
    }
}
